# Generated by Django 2.0.6 on 2018-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
