# Generated by Django 2.0.6 on 2018-07-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0002_sublet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='title',
            field=models.CharField(default='A fine place to live', max_length=50),
            preserve_default=False,
        ),
    ]
