# Generated by Django 2.0.6 on 2018-07-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0002_auto_20180711_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
