# Generated by Django 2.0.6 on 2018-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0004_sublet_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(default='static/images/example.jpg', upload_to='images/'),
        ),
    ]
