# Generated by Django 2.0.6 on 2018-07-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0005_auto_20180714_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(default='images/example.jpg', upload_to='images/'),
        ),
    ]
