# Generated by Django 2.0.6 on 2018-07-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0006_auto_20180714_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(default='subby_project/images/example.jpg', upload_to='images/'),
        ),
    ]
