# Generated by Django 2.0.6 on 2018-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0008_sublet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
