# Generated by Django 2.0.6 on 2018-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0011_remove_sublet_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(default='media/images/example.jpg', upload_to='images/'),
        ),
    ]
