# Generated by Django 2.0.6 on 2018-07-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0012_sublet_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
