# Generated by Django 2.0.6 on 2018-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0013_auto_20180716_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublet101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_input', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('choice', models.CharField(choices=[('W', 'Walking'), ('T', 'Transit'), ('D', 'Walking')], max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('postal_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sublet',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
