# Generated by Django 2.0.6 on 2018-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0013_auto_20180716_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sublet',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
