# Generated by Django 2.0.6 on 2018-07-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0014_auto_20180717_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublet101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FloatField()),
            ],
        ),
    ]
