# Generated by Django 2.0.6 on 2018-07-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0015_sublet101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sublet101',
        ),
    ]
