# Generated by Django 2.0.6 on 2018-07-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0016_delete_sublet101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubletImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sublet',
            name='front_image',
        ),
        migrations.AddField(
            model_name='subletimage',
            name='sublet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subby.Sublet'),
        ),
    ]
