# Generated by Django 2.0.6 on 2018-07-21 02:46

from django.db import migrations, models
import subby.managers.ratingmanager


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0019_auto_20180719_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.PositiveIntegerField()),
                ('reviewed_user_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('objects', subby.managers.ratingmanager.RatingManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='sublet',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
