# Generated by Django 2.0.6 on 2018-07-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0020_auto_20180721_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublet',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='sublet',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sublet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
