# Generated by Django 2.0.6 on 2018-07-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import subby.managers.ratingmanager


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0021_auto_20180721_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', subby.managers.ratingmanager.RatingManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'reviewed_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rating1',
            unique_together={('reviewer', 'reviewee')},
        ),
    ]
