# Generated by Django 2.0.6 on 2018-07-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0022_auto_20180728_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating1',
            old_name='reviewee',
            new_name='reviewed_user',
        ),
        migrations.RenameField(
            model_name='rating1',
            old_name='reviewer',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating1',
            unique_together={('user', 'reviewed_user')},
        ),
    ]
