# Generated by Django 2.0.6 on 2018-07-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0023_auto_20180728_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating1',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating1',
            name='reviewed_user',
        ),
        migrations.RemoveField(
            model_name='rating1',
            name='user',
        ),
        migrations.AlterField(
            model_name='sublet',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rating1',
        ),
    ]
