# Generated by Django 2.0.6 on 2018-08-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0025_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='sublet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subby.Sublet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
