# Generated by Django 2.0.6 on 2018-08-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0027_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sublet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='subby.Sublet'),
        ),
        migrations.AlterField(
            model_name='subletimage',
            name='sublet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublet_image', to='subby.Sublet'),
        ),
    ]
