# Generated by Django 2.0.6 on 2018-08-03 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0028_auto_20180803_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublets', to=settings.AUTH_USER_MODEL),
        ),
    ]
